package com.example.chokabara

import com.chokabarah.game.engine.CowryResult
import com.chokabarah.game.engine.GridSize
import com.chokabarah.game.engine.Pawn
import com.chokabarah.game.engine.PawnState
import com.chokabarah.game.engine.TrackBuilder
import com.chokabarah.game.engine.calculateValidMoves
import com.chokabarah.game.engine.executeMovePure
import com.chokabarah.game.engine.scoreShells
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

// ============================================================
// Differential parity test: Kotlin engine vs. frozen JS corpus.
// ------------------------------------------------------------
// Reads web/parity/parity-corpus.json (copied into
// engine/src/test/resources/parity/), generated by the reference
// web/game-engine.js via `node web/scripts/gen-parity-corpus.js`,
// and asserts the pure Kotlin rule surface produces identical
// output: TrackBuilder paths + safe cells, scoreShells cowry
// scoring, and calculateValidMoves (home entry, gate, overshoot,
// capture, Gatti, reach-home) — both board sizes.
//
// The generator writes BOTH web/parity/parity-corpus.json AND this
// resource copy in ONE run, so they never drift. Regenerate with:
//   node web/scripts/gen-parity-corpus.js
// ============================================================
class EngineParityTest {

    private fun corpus(): JSONObject {
        val stream = javaClass.classLoader.getResourceAsStream("parity/parity-corpus.json")
            ?: throw IllegalStateException("parity/parity-corpus.json missing from test resources")
        return JSONObject(stream.readBytes().toString(Charsets.UTF_8))
    }

    private fun gridSize(s: Int): GridSize =
        if (s == 5) GridSize.FIVE_BY_FIVE else GridSize.SEVEN_BY_SEVEN

    private fun stateName(s: String): PawnState = when (s) {
        "HOME_BASE" -> PawnState.HOME_BASE
        "ON_TRACK"  -> PawnState.ON_TRACK
        "FINISHED"  -> PawnState.FINISHED
        else -> throw IllegalArgumentException("Unknown state $s")
    }

    @Test
    fun pathsMatchCorpus() {
        // Every (gridSize, playerIndex) path cell must equal the JS-derived corpus.
        val json = corpus()
        val arr = json.getJSONArray("paths")
        for (i in 0 until arr.length()) {
            val entry = arr.getJSONObject(i)
            val gridSize = gridSize(entry.getInt("gridSize"))
            val playerIndex = entry.getInt("playerIndex")
            val cells = entry.getJSONArray("cells")
            val kotlin = TrackBuilder.getPlayerPath(gridSize, playerIndex)
            assertEquals("path length P$playerIndex", cells.length(), kotlin.size)
            for (j in 0 until cells.length()) {
                val cell = cells.getJSONArray(j)
                val k = kotlin[j]
                assertEquals("path P$playerIndex cell $j", listOf(cell.getInt(0), cell.getInt(1)), listOf(k.first, k.second))
            }
        }
    }

    @Test
    fun safeCellsMatchCorpus() {
        // Recompute the safe-square set from TrackBuilder and compare with corpus.
        val safe = corpus().getJSONObject("safeCells")
        for (s in intArrayOf(5, 7)) {
            val gridSize = gridSize(s)
            val kotlin = mutableListOf<List<Int>>()
            for (r in 0 until s) {
                for (c in 0 until s) {
                    if (TrackBuilder.isSafeCell(gridSize, r, c)) kotlin.add(listOf(r, c))
                }
            }
            val expected = safe.getJSONArray(s.toString()).toCellList()
            assertEquals("safe cells $s x $s", expected, kotlin)
        }
    }

    @Test
    fun cowryScoringMatchesCorpus() {
        // Every shell pattern (4 & 6 shells) must score identically to the JS engine.
        val arr = corpus().getJSONArray("cowryRolls")
        for (i in 0 until arr.length()) {
            val entry = arr.getJSONObject(i)
            val shells = entry.getJSONArray("shells").toBooleanList()
            val expectedScore = entry.getInt("score")
            val expectedExtra = entry.getBoolean("isExtraRoll")
            val result = scoreShells(shells)
            assertEquals("score shells=$shells", expectedScore, result.score)
            assertEquals("isExtraRoll shells=$shells", expectedExtra, result.isExtraRoll)
        }
    }

    @Test
    fun cowryScoringExtraRollFlag() {
        // Spot-check Chowka/Baara extra-roll flags on both board sizes.
        assertTrue(scoreShells(listOf(true, true, true, true)).isExtraRoll)
        assertTrue(scoreShells(listOf(false, false, false, false)).isExtraRoll)
        assertFalse(scoreShells(listOf(true, true, false, false)).isExtraRoll)
        assertTrue(scoreShells(listOf(true, true, true, true, true, true)).isExtraRoll)
        assertTrue(scoreShells(listOf(false, false, false, false, false, false)).isExtraRoll)
    }

    @Test
    fun validMovesMatchCorpus() {
        // Deterministic board states (home entry, gate, capture, Gatti, home reach)
        // must produce the SAME move set (ids, targets, capture/home/gatti flags) as JS.
        val arr = corpus().getJSONArray("validMoves")
        for (i in 0 until arr.length()) {
            val scen = arr.getJSONObject(i)
            val gridSize = gridSize(scen.getInt("gridSize"))
            val player = scen.getInt("player")
            val score = scen.getInt("score")

            val pawns = mutableListOf<Pawn>()
            val pawnArr = scen.getJSONArray("pawns")
            for (k in 0 until pawnArr.length()) {
                val p = pawnArr.getJSONObject(k)
                pawns.add(
                    Pawn(
                        id = p.getInt("id"),
                        playerIndex = p.getInt("playerIndex"),
                        state = stateName(p.getString("state")),
                        pathIndex = p.getInt("pathIndex")
                    )
                )
            }

            val hasCaptured = mutableMapOf<Int, Boolean>()
            val cap = scen.getJSONObject("hasCaptured")
            cap.keys().forEach { key -> hasCaptured[key.toInt()] = cap.getBoolean(key) }

            val kotlin = calculateValidMoves(gridSize, pawns, player, hasCaptured, score)
            val expectedArr = scen.getJSONArray("expected")

            assertEquals("scenario ${scen.optString("label", "scen${i + 1}")} move count", expectedArr.length(), kotlin.size)
            for (j in 0 until expectedArr.length()) {
                val exp = expectedArr.getJSONObject(j)
                val m = kotlin[j]
                assertEquals("scen$i pawnIds", exp.getJSONArray("pawnIds").toIntList(), m.grpPawns.map { it.id })
                assertEquals("scen$i targetPathIndex", exp.getInt("targetPathIndex"), m.targetPathIndex)
                val coords = exp.getJSONArray("targetCoords")
                assertEquals("scen$i targetCoords", listOf(coords.getInt(0), coords.getInt(1)), listOf(m.targetCoords.first, m.targetCoords.second))
                assertEquals("scen$i isCapture", exp.getBoolean("isCapture"), m.isCapture)
                assertEquals("scen$i reachesHome", exp.getBoolean("reachesHome"), m.reachesHome)
                assertEquals("scen$i isGattiGroup", exp.getBoolean("isGattiGroup"), m.isGattiGroup)
            }
        }
    }

    @Test
    fun executeMoveMatchesCorpus() {
        // Full move-execution differential: replay each frozen scenario through
        // the pure Kotlin executor and compare pawn states, capture flags,
        // winner, extra-turn and Gatti outcomes with the JS reference.
        val arr = corpus().getJSONArray("moveExecutions")
        for (i in 0 until arr.length()) {
            val scen = arr.getJSONObject(i)
            val label = scen.optString("label", "moveExec$i")
            val gridSize = gridSize(scen.getInt("gridSize"))
            val player = scen.getInt("player")

            val pawnsBefore = mutableListOf<Pawn>()
            val pawnArr = scen.getJSONArray("pawnsBefore")
            for (k in 0 until pawnArr.length()) {
                val p = pawnArr.getJSONObject(k)
                pawnsBefore.add(Pawn(p.getInt("id"), p.getInt("playerIndex"), stateName(p.getString("state")), p.getInt("pathIndex")))
            }

            val hasCapturedBefore = mutableMapOf<Int, Boolean>()
            val cap = scen.getJSONObject("hasCapturedBefore")
            cap.keys().forEach { key -> hasCapturedBefore[key.toInt()] = cap.getBoolean(key) }

            val mv = scen.getJSONObject("move")
            val ids = mv.getJSONArray("pawnIds").toIntList()
            val coords = mv.getJSONArray("targetCoords")
            val liveMove = com.chokabarah.game.engine.MoveOption(
                grpPawns = pawnsBefore.filter { it.id in ids },
                targetPathIndex = mv.getInt("targetPathIndex"),
                targetCoords = coords.getInt(0) to coords.getInt(1),
                isCapture = mv.getBoolean("isCapture"),
                reachesHome = mv.getBoolean("reachesHome"),
                isGattiGroup = mv.getBoolean("isGattiGroup")
            )
            val roll: CowryResult? = if (scen.getBoolean("rollIsExtraRoll")) {
                CowryResult(emptyList(), 0, true, "corpus")
            } else {
                CowryResult(emptyList(), 0, false, "corpus")
            }

            val res = executeMovePure(gridSize, pawnsBefore, hasCapturedBefore, player, liveMove, roll)
            assertNull("${label} error", res.error)

            val expected = scen.getJSONObject("expected")
            val pawnsAfter = expected.getJSONArray("pawnsAfter")
            assertEquals("$label pawn count", pawnsAfter.length(), res.pawns.size)
            for (k in 0 until pawnsAfter.length()) {
                val p = pawnsAfter.getJSONObject(k)
                val kp = res.pawns.first { it.id == p.getInt("id") }
                assertEquals("$label pawn ${p.getInt("id")} playerIndex", p.getInt("playerIndex"), kp.playerIndex)
                assertEquals("$label pawn ${p.getInt("id")} state", stateName(p.getString("state")), kp.state)
                assertEquals("$label pawn ${p.getInt("id")} pathIndex", p.getInt("pathIndex"), kp.pathIndex)
            }

            val capturedAfter = expected.getJSONObject("hasCapturedAfter")
            assertEquals(
                "$label hasCaptured",
                capturedAfter.keys().asSequence().map { it.toInt() to capturedAfter.getBoolean(it) }.toMap(),
                res.hasCapturedOpponent
            )
            assertEquals("$label winnerIndex", expected.getInt("winnerIndex"), res.winnerIndex)
            assertEquals("$label extraTurn", expected.getBoolean("extraTurn"), res.extraTurn)
            assertEquals("$label gattiFormed", expected.getBoolean("gattiFormed"), res.gattiFormed)
            assertEquals("$label capturedCount", expected.getInt("capturedCount"), res.capturedCount)
            assertEquals("$label reachesHome", expected.getBoolean("reachesHome"), res.reachesHome)
        }
    }

    private fun JSONArray.toCellList(): List<List<Int>> {
        val out = mutableListOf<List<Int>>()
        for (i in 0 until length()) {
            val c = getJSONArray(i)
            out.add(listOf(c.getInt(0), c.getInt(1)))
        }
        return out
    }

    private fun JSONArray.toIntList(): List<Int> {
        val out = mutableListOf<Int>()
        for (i in 0 until length()) out.add(getInt(i))
        return out
    }

    private fun JSONArray.toBooleanList(): List<Boolean> {
        val out = mutableListOf<Boolean>()
        for (i in 0 until length()) out.add(getBoolean(i))
        return out
    }
}